### ISSUE TITLE
no-echo parameter

### ISSUE THREAD

**Issue by deesnow** [deesnow/ossi_tool#5]
Removal of command repetition from console and output CSV file.

```
77709,1  2  3
77708,1
77707,1  2

instead of that:
-------- 
list bridged-extensions 77702
--------
77709,1  2  3
-------- 
list bridged-extensions 77703
--------
77708,1
-------- 
list bridged-extensions 77704
--------
77707,1  2

**Comment by deesnow** [comment]
@fiodorpugach 
The requested feature is implemented in 0.3.3.4
Update ossi with 'sudo pip install --upgrade ossi_tool'

**Comment by fiodorpugach** [comment]
It works, thank you! It will be completely perfect if you remove empty rows to look like that:
77709,1  2  3
77708,1
77707,1  2
instead of that:
77709,1  2  3

77708,1

77707,1  2

Thank you for your work with this tool!

**Comment by deesnow** [comment]
> It works, thank you! It will be completely perfect if you remove empty rows to look like that:
> 77709,1 2 3
> 77708,1
> 77707,1 2
> instead of that:
> 77709,1 2 3
> 
> 77708,1
> 
> 77707,1 2
> 
> Thank you for your work with this tool!

If I remove the empty line than cannot recognize where is the end of a command output in case of multiple commands, because some commands have multiple line as output.
I would like to keep all option general for all type of command.

**Comment by fiodorpugach** [comment]
Understood and agree about empty line. One more thing. Yesterday I run ossi-tool to query bridged appearances on 12000 stations. It took around 7 hours because of 2 seconds timeout between command executions. Report query from ASA 'display station 00000 count 12000' takes only 5 minutes for the same 12000 stations. Is it possible to reduce inter-command timeout at least to 0.2 seconds, or make another switch so user will be able to put timeout of his choice based on system performance? Than k you!

**Comment by deesnow** [comment]
> Understood and agree about empty line. One more thing. Yesterday I run ossi-tool to query bridged appearances on 12000 stations. It took around 7 hours because of 2 seconds timeout between command executions. Report query from ASA 'display station 00000 count 12000' takes only 5 minutes for the same 12000 stations. Is it possible to reduce inter-command timeout at least to 0.2 seconds, or make another switch so user will be able to put timeout of his choice based on system performance? Than k you!

I have added it as new feature request:
https://github.com/deesnow/ossi_tool/issues/6

But closing this one.
